# Generated by Django 4.2.10 on 2025-03-19 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='My Watchlist', max_length=100),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(related_name='watchlists', to='dashboard.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('name', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
    ]
