# Generated by Django 4.2.10 on 2025-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_watchlist_created_by_watchlist_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='current_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='dashboard_s_symbol_1ad46f_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['isin'], name='dashboard_s_isin_d501ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='dashboard_s_sector_47e77f_idx'),
        ),
    ]
