# Generated by Django 4.2.10 on 2025-03-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_stock_options_remove_stock_current_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='dashboard.stock'),
        ),
    ]
