# Generated by Django 4.2.10 on 2025-03-25 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
