# Generated by Django 4.2.10 on 2025-04-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_riskanalysis_marketinsight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskanalysis',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MarketInsight',
        ),
        migrations.DeleteModel(
            name='RiskAnalysis',
        ),
    ]
