# Generated by Django 4.2.10 on 2025-04-12 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_remove_riskanalysis_created_by_delete_marketinsight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('field_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('column_type', models.CharField(choices=[('basic', 'Basic Stock Info'), ('price', 'Price Data'), ('technical', 'Technical Indicator'), ('fundamental', 'Fundamental Data'), ('custom', 'Custom Calculation')], default='basic', max_length=20)),
                ('data_field', models.CharField(blank=True, help_text='Field name in the data source model', max_length=50)),
                ('calculation_formula', models.TextField(blank=True, help_text='Python expression for custom calculations')),
                ('is_default', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('format_string', models.CharField(blank=True, help_text="Format string for displaying the value (e.g., '{:.2f}' for 2 decimal places)", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'display_name'],
                'permissions': [('manage_watchlist_columns', 'Can manage watchlist columns')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.JSONField(blank=True, default=dict, help_text='JSON field to store custom column order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('columns', models.ManyToManyField(related_name='user_settings', to='dashboard.watchlistcolumn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_display_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
