# Generated by Django 4.2.10 on 2025-04-12 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_watchlistcolumn_watchlistdisplaysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistdisplaysettings',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='watchlistdisplaysettings',
            name='watchlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='dashboard.watchlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlistdisplaysettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_display_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistdisplaysettings',
            unique_together={('user', 'watchlist')},
        ),
    ]
