# Generated by Django 4.2.10 on 2025-05-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_watchlistdisplaysettings_options_and_more'),
        ('dashboard', '0011_dashboard_stockprice'),
    ]

    operations = [
    ]
